/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** DBX Client Configuration */
export interface DbxConfig {
  /** DBX API base URL (e.g., "http://localhost:3000") */
  baseUrl: string
  /** Authentication username (optional for API key auth) */
  username?: string
  /** Authentication password (optional for API key auth) */
  password?: string
  /** API key for authentication (alternative to username/password) */
  apiKey?: string
  /** Request timeout in milliseconds (default: 30000) */
  timeoutMs?: number
  /** Maximum retry attempts (default: 3) */
  maxRetries?: number
  /** Retry delay in milliseconds (default: 1000) */
  retryDelayMs?: number
  /** Connection pool size (default: 10) */
  poolSize?: number
  /** Enable automatic token refresh (default: true) */
  autoRefreshToken?: boolean
  /** Enable request logging (default: false) */
  enableLogging?: boolean
}
/** API Response Structure */
export interface DbxResponse {
  success: boolean
  data?: string
  error?: string
  operationId?: string
  executionTimeMs?: number
  backend?: string
  metadata?: string
}
/** Query Response Structure */
export interface DbxQueryResponse {
  success: boolean
  queryId: string
  results: Array<DbxQueryResult>
  totalCount?: number
  executionTimeMs?: number
  backend?: string
  error?: string
}
/** Query Result Item */
export interface DbxQueryResult {
  key: string
  data: string
  score?: number
}
/** Batch Operation Request */
export interface DbxBatchOperation {
  operationType: string
  key: string
  value?: string
  fields?: string
  ttl?: number
}
/** API Key Information */
export interface DbxApiKey {
  id: string
  name: string
  keyPrefix: string
  permissions: Array<string>
  expiresAt?: string
  createdAt: string
  lastUsed?: string
  isActive: boolean
}
/** Role Information */
export interface DbxRole {
  name: string
  permissions: Array<string>
  description?: string
  inheritsFrom: Array<string>
  createdAt: string
  updatedAt: string
  isSystemRole: boolean
}
/** User Role Assignment */
export interface DbxUserRoleAssignment {
  userId: string
  username: string
  roleName: string
  assignedBy: string
  assignedAt: string
  expiresAt?: string
  isActive: boolean
}
/** Rate Limit Policy */
export interface DbxRateLimitPolicy {
  identifier: string
  policyType: string
  requests: number
  windowSeconds: number
  burstAllowance?: number
  createdAt: string
  updatedAt: string
}
/** Rate Limit Status */
export interface DbxRateLimitStatus {
  identifier: string
  requestsMade: number
  requestsRemaining: number
  windowResetTime: string
  burstAvailable?: number
}
/** System Health Information */
export interface DbxSystemHealth {
  status: string
  version: string
  uptimeSeconds: string
  backends: string
  memoryUsage?: string
  activeConnections?: number
}
/** WebSocket Configuration */
export interface DbxWebSocketConfig {
  url: string
  reconnectAttempts?: number
  reconnectDelayMs?: number
  pingIntervalMs?: number
  maxMessageSize?: number
}
/** Stream Configuration */
export interface DbxStreamConfig {
  streamName: string
  maxLen?: number
  retentionMs?: string
  consumerGroup?: string
  consumerName?: string
}
/** DBX TypeScript Client */
export declare class DbxClient {
  /** Create a new DBX client */
  constructor(config: DbxConfig)
  /** Authenticate with username and password */
  authenticate(username: string, password: string): Promise<boolean>
  /** Refresh authentication token */
  refreshAuthToken(): Promise<boolean>
  /** Logout and clear tokens */
  logout(): Promise<boolean>
  /** Set a value for a key with optional TTL */
  set(key: string, value: string, ttl?: number | undefined | null): Promise<DbxResponse>
  /** Get a value by key */
  get(key: string): Promise<DbxResponse>
  /** Update fields for a key (hash operations) */
  update(key: string, fieldsJson: string, ttl?: number | undefined | null): Promise<DbxResponse>
  /** Delete a key */
  delete(key: string): Promise<DbxResponse>
  /** Check if a key exists */
  exists(key: string): Promise<DbxResponse>
  /** Execute batch operations */
  batch(operations: Array<DbxBatchOperation>): Promise<DbxResponse>
  /** Execute multiple get operations */
  batchGet(keys: Array<string>): Promise<DbxResponse>
  /** Execute multiple set operations */
  batchSet(items: Array<[string, string, number | undefined | null]>): Promise<DbxResponse>
  /** Execute multiple delete operations */
  batchDelete(keys: Array<string>): Promise<DbxResponse>
  /** Search by key pattern */
  queryPattern(pattern: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<DbxQueryResponse>
  /** Text search across data */
  queryText(query: string, fields?: Array<string> | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<DbxQueryResponse>
  /** Health check (public endpoint) */
  health(): Promise<DbxResponse>
  /** Get current authentication status */
  isAuthenticated(): Promise<boolean>
  /** Get current configuration */
  getConfig(): DbxConfig
  /** Validate current session */
  validateSession(): Promise<boolean>
  /** Get TTL for a key */
  getTtl(key: string): Promise<DbxResponse>
  /** Set TTL for a key */
  setTtl(key: string, ttlSeconds: number): Promise<DbxResponse>
  /** Increment a numeric value */
  increment(key: string, amount?: number | undefined | null): Promise<DbxResponse>
  /** Decrement a numeric value */
  decrement(key: string, amount?: number | undefined | null): Promise<DbxResponse>
  /** Append to a string value */
  append(key: string, value: string): Promise<DbxResponse>
  /** Get length of a value */
  length(key: string): Promise<DbxResponse>
  /** Set value if key does not exist */
  setIfNotExists(key: string, value: string, ttl?: number | undefined | null): Promise<DbxResponse>
  /** Compare and swap operation */
  compareAndSwap(key: string, expectedValue: string, newValue: string, ttl?: number | undefined | null): Promise<DbxResponse>
  /** Auto-refresh token if needed */
  autoRefreshIfNeeded(): Promise<void>
}
